// AUTO-GENERATED by scripts/state-to-scene.mjs. Do not edit by hand.
// Re-run the generator after editing state.json.

import { gsap } from "https://esm.sh/gsap@3.15.0";
import GSDevTools from "https://esm.sh/gsap@3.15.0/GSDevTools";
import SplitText from "https://esm.sh/gsap@3.15.0/SplitText";
import { get as primitiveGet } from "../../skills/motion-primitives/index.js";
import { validate, at as stateAt, add as stateAdd, remove as stateRm, update as stateUp, summary as stateSummary } from "../../skills/motion-state/runtime.mjs";

const beat_0 = {"id":"b1","layerId":"bg","primitive":"fadeIn","at":0,"duration":0.6};
const beat_1 = {"id":"b2","layerId":"logo","primitive":"scaleIn","at":0.3,"duration":0.6,"args":{"from":0.6}};
const beat_2 = {"id":"b3","layerId":"eyebrow","primitive":"fadeUp","at":0.9,"duration":0.5};
const beat_3 = {"id":"b4","layerId":"headline","primitive":"splitReveal","at":1.3,"duration":0.9,"args":{"direction":"up","stagger":0.08}};
const beat_4 = {"id":"b5","layerId":"sub","primitive":"fadeUp","at":2.4,"duration":0.6,"allowOverlap":true};
const beat_5 = {"id":"b6","layerId":"cta","primitive":"slideInLeft","at":3.2,"duration":0.6};

const STATE = {
  "schemaVersion": 1,
  "slug": "product-hero-reveal",
  "title": "Product Hero Reveal",
  "industry": "product",
  "duration": 6,
  "fps": 30,
  "width": 1080,
  "height": 1920,
  "accent": "#FF5A1F",
  "layers": [
    {
      "id": "bg",
      "selector": ".bg-shape",
      "type": "any",
      "content": ""
    },
    {
      "id": "logo",
      "selector": ".logo",
      "type": "any",
      "content": ""
    },
    {
      "id": "eyebrow",
      "selector": ".eyebrow",
      "type": "text",
      "content": "NEW DROP"
    },
    {
      "id": "headline",
      "selector": ".headline",
      "type": "text",
      "content": "Made to Move"
    },
    {
      "id": "sub",
      "selector": ".subhead",
      "type": "text",
      "content": "The lightest runner we have ever made."
    },
    {
      "id": "cta",
      "selector": ".cta",
      "type": "text",
      "content": "SHOP NOW"
    }
  ],
  "beats": [
    {
      "id": "b1",
      "layerId": "bg",
      "primitive": "fadeIn",
      "at": 0,
      "duration": 0.6
    },
    {
      "id": "b2",
      "layerId": "logo",
      "primitive": "scaleIn",
      "at": 0.3,
      "duration": 0.6,
      "args": {
        "from": 0.6
      }
    },
    {
      "id": "b3",
      "layerId": "eyebrow",
      "primitive": "fadeUp",
      "at": 0.9,
      "duration": 0.5
    },
    {
      "id": "b4",
      "layerId": "headline",
      "primitive": "splitReveal",
      "at": 1.3,
      "duration": 0.9,
      "args": {
        "direction": "up",
        "stagger": 0.08
      }
    },
    {
      "id": "b5",
      "layerId": "sub",
      "primitive": "fadeUp",
      "at": 2.4,
      "duration": 0.6,
      "allowOverlap": true
    },
    {
      "id": "b6",
      "layerId": "cta",
      "primitive": "slideInLeft",
      "at": 3.2,
      "duration": 0.6
    }
  ]
};
validate(STATE);

const layerMap = {
  "bg": ".bg-shape",
  "logo": ".logo",
  "eyebrow": ".eyebrow",
  "headline": ".headline",
  "sub": ".subhead",
  "cta": ".cta"
};

const STAGE = document.querySelector(".stage");
const els = {};
for (const [id, sel] of Object.entries(layerMap)) {
  els[id] = STAGE.querySelector(sel);
}

let currentState = STATE;
let tl;

function buildTimeline() {
  const t = gsap.timeline();
  const beats = [    {
         id: "b1",
         apply() {
           const _p = primitiveGet("fadeIn");
           const _args = { ...(_p.defaultArgs ?? {}), ...({}) };
           _p.apply(els["bg"], _args, { tl, gsap, beat: beat_0, state });
         }
       },
      {
         id: "b2",
         apply() {
           const _p = primitiveGet("scaleIn");
           const _args = { ...(_p.defaultArgs ?? {}), ...({"from":0.6}) };
           _p.apply(els["logo"], _args, { tl, gsap, beat: beat_1, state });
         }
       },
      {
         id: "b3",
         apply() {
           const _p = primitiveGet("fadeUp");
           const _args = { ...(_p.defaultArgs ?? {}), ...({}) };
           _p.apply(els["eyebrow"], _args, { tl, gsap, beat: beat_2, state });
         }
       },
      {
         id: "b4",
         apply() {
           const _p = primitiveGet("splitReveal");
           const _args = { ...(_p.defaultArgs ?? {}), ...({"direction":"up","stagger":0.08}) };
           _p.apply(els["headline"], _args, { tl, gsap, beat: beat_3, state });
         }
       },
      {
         id: "b5",
         apply() {
           const _p = primitiveGet("fadeUp");
           const _args = { ...(_p.defaultArgs ?? {}), ...({}) };
           _p.apply(els["sub"], _args, { tl, gsap, beat: beat_4, state });
         }
       },
      {
         id: "b6",
         apply() {
           const _p = primitiveGet("slideInLeft");
           const _args = { ...(_p.defaultArgs ?? {}), ...({}) };
           _p.apply(els["cta"], _args, { tl, gsap, beat: beat_5, state });
         }
       }];
  for (const b of beats) b.apply();
  return t;
}

gsap.matchMedia().add({
  isMotionOK: "(prefers-reduced-motion: no-preference)"
}, () => {
  tl = buildTimeline();
  window.__studio = {
    gsap, tl,
    duration: () => tl.duration(),
    state: currentState,
    summary: () => stateSummary(currentState),
    at: (t) => stateAt(currentState, t),
    add: (beat) => { currentState = stateAdd(currentState, beat); rebuild(); },
    remove: (id) => { currentState = stateRm(currentState, id); rebuild(); },
    update: (id, patch) => { currentState = stateUp(currentState, id, patch); rebuild(); }
  };
  if (!window.__RENDERING) {
    gsap.registerPlugin(GSDevTools);
    if (window.__studio.tl) {
      GSDevTools.create({ animation: tl, container: "#devtools" });
    }
  }
  window.dispatchEvent(new Event("__studio:ready"));
  return () => { tl?.kill(); };
});

function rebuild() {
  // Tear down + rebuild tl from currentState.
  tl?.kill();
  const next = buildTimeline();
  tl = next;
  window.__studio.tl = next;
  window.__studio.state = currentState;
  GSDevTools?.get()?.destroy?.();
  if (!window.__RENDERING && window.__studio.tl) {
    GSDevTools.create({ animation: next, container: "#devtools" });
  }
}
